import { StyleSheet } from 'react-native';
// import { Color } from '../../components/Colors';
import { Colors } from '../../constants/Colors';
const styles = StyleSheet.create({
    container_center: {
        flex: 1,
        padding: 30,
        justifyContent: 'center',
        backgroundColor: Colors.light.background,
        width: '100%',
        height: '100%',
        position: 'relative',
    },
    container_top: {
        flex: 1,
        padding: 16,
        backgroundColor: '#f4f4f4',
        width: '100%',
        height: '100%',
        paddingTop: 220,
        paddingBottom: 40,
        justifyContent: 'flex-start',
    },
    input: {
        padding: 8,
        marginBottom: 12,
        fontSize: 16,
        backgroundColor: '#fff',
        fontFamily: 'Kanit400',
        width: '100%',
        borderWidth: 1,
        borderBottomColor: '#ccc',
        borderRadius: 6,
    },
    button_green: {
        backgroundColor: '#2e6b50',
        paddingVertical: 14,
        borderRadius: 4,
        alignItems: 'center',
        marginBottom: 15,
    },
    button_green_text: {
        color: '#fff',
        fontSize: 16,
        fontFamily: 'Kanit400',
    },
    button_white: {
        backgroundColor: '#fff',
        borderRadius: 4,
        borderColor: '#ddd',
        borderWidth: 1,
        paddingVertical: 12,
        alignItems: 'center',
        marginBottom: 20,
    },
    button_gray: {
        backgroundColor: '#eaeaea',
        paddingVertical: 14,
        borderRadius: 4,
        alignItems: 'center',
    },
    button_gray_text: {
        color: '#888',
        fontSize: 16,
        fontFamily: 'Kanit400',
    },
    nextIcon: {
        position: 'absolute',
        bottom: 25,
        right: 25,
        display: 'flex',
        alignItems: 'center',
        flexDirection: 'row',
    },
    nextIcon_Text: {
        fontSize: 24,
        color: '#000',
        fontFamily: 'Kanit400',
        marginRight: 10,
    },
})

const home_styles = StyleSheet.create({
    viewmain: {
        width: '100%',
        height: '100%',
        position: 'relative',
        justifyContent: 'flex-start',
        alignItems: 'center',
    },
    scrollmain: {
        width: '100%',
        height: '100%',
        position: 'relative',
    },
    container: {
        flex: 1,
        padding: 16,
        backgroundColor: Colors.light.background,
        width: '100%',
        height: '100%',
        paddingTop: 220,
        paddingBottom: 40,
        justifyContent: 'flex-start',
    },
    header: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'flex-end',
        alignItems: 'center',
        paddingVertical: 10,
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        height: 180,
        borderBottomRightRadius: 20,
        borderBottomLeftRadius: 20,
    },

    headerBackground: {
        position: 'absolute',
        left: 0,
        right: 0,
        height: 180,
        width: '100%',
    },

    headerText: {
        backgroundColor: '#fff',
        borderRadius: 50,
        paddingHorizontal: 24,
        paddingVertical: 8,
        display: 'flex',
        position: 'absolute',
        bottom: -20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 4,
        right: '50%',
        transform: [{ translateX: '50%' }],
    },

    headerImage: {
        width: '20%',
        height: '70%',
        resizeMode: 'contain',
        alignSelf: 'flex-end',
        position: 'absolute',
        bottom: 20,
        right: 0,
        marginHorizontal: 30,
    },
    calendar: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'stretch',
        borderRadius: 10,
        paddingHorizontal: 10,
    },
    calendar_head: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginVertical: 6,
    },
    listItem: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        padding: 18,
        backgroundColor: Colors.light.main,
        borderRadius: 50,
        aspectRatio: 1,
    },
    listItem_disabled: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        padding: 18,
        backgroundColor: '#0f513200',
        borderRadius: 50,
        aspectRatio: 1,
    },
    listItemText: {
        fontSize: 20,
        color: '#fff',
        fontFamily: 'Kanit400',
        padding: 0,
        margin: 0,
        textAlign: 'center',
        position: 'absolute',
    },
    listItemText_disabled: {
        fontSize: 20,
        color: '#aaa',
        fontFamily: 'Kanit400',
        padding: 0,
        margin: 0,
        textAlign: 'center',
        position: 'absolute',
    },
    listIconDone: {
        color: 'green',
        fontSize: 25,
    },
    listIconNot: {
        color: 'red',
        fontSize: 25,
    },
    listIconNow: {
        color: '#999',
        fontSize: 20,
        paddingBottom: 2,
    },
    input: styles.input,
});

const cardtodo_styles = StyleSheet.create({
    card: {
        marginTop: 18,
        marginBottom: 12,
        padding: 16,
        borderRadius: 10,
        backgroundColor: '#fff',
        borderColor: '#eaeaea',
        borderWidth: 1,
        borderBottomWidth: 2,
        borderTopWidth: 0,
    },
    card_header: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 10,
    },
    card_header_text: {
        fontSize: 16,
        fontFamily: 'Kanit400',
        color: '#000000ff',
        margin: 0,
        padding: 0,
    },
    card_header_icon: {
        fontSize: 18,
        fontFamily: 'Kanit300',
        color: '#000000ff',
        margin: 0,
        padding: 0,
    },
    title: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#0f5132',
        marginBottom: 10,
    },
    taskRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 2,
        backgroundColor: '#eaeaea',
        width: '100%',
        paddingVertical: 4,
        paddingHorizontal: 16,
        borderRadius: 50,
        marginVertical: 1,
    },
    taskRow_completed: {
        textDecorationLine: 'line-through',
        backgroundColor: '#4CB59144',
        color: '#555',
    },
    taskRow_change: {
        textDecorationLine: 'line-through',
        backgroundColor: Colors.light.bg_warning,
        color: '#555',
    },
    taskText: {
        fontSize: 16,
        fontFamily: 'Kanit300',
    },
    taskText_completed: {
        fontSize: 16,
        fontFamily: 'Kanit300',
        color: '#4CB591',
    },
    completed: {
        textDecorationLine: 'line-through',
        color: '#4CB591',
    },
    divider: {
        height: 1,
        backgroundColor: '#ccc',
        marginVertical: 10,
    },
    bottomRightIcon: {
        position: 'absolute',
        bottom: 20,
        right: 20,
        backgroundColor: Colors.light.main,
        padding: 10,
        borderRadius: 50,
    },
});

export default { home_styles, cardtodo_styles };